/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author kaick_6nllywo
 */
public class MainInterface extends javax.swing.JFrame {

    /**
     * Creates new form MainInterface
     */
    public MainInterface() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        aScroll = new javax.swing.JSlider();
        bScroll = new javax.swing.JSlider();
        cScroll = new javax.swing.JSlider();
        aView = new javax.swing.JLabel();
        bView = new javax.swing.JLabel();
        cView = new javax.swing.JLabel();
        Result = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel1.setText("Lado A");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        jLabel2.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel2.setText("Lado B");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 29, -1, -1));

        jLabel3.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel3.setText("Lado C");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 52, -1, -1));

        aScroll.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
                aScrollAncestorMoved(evt);
            }
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
                aScrollAncestorAdded(evt);
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
        });
        aScroll.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                aScrollStateChanged(evt);
            }
        });
        getContentPane().add(aScroll, new org.netbeans.lib.awtextra.AbsoluteConstraints(57, 0, 203, 14));

        bScroll.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                bScrollStateChanged(evt);
            }
        });
        getContentPane().add(bScroll, new org.netbeans.lib.awtextra.AbsoluteConstraints(58, 29, -1, 14));

        cScroll.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                cScrollStateChanged(evt);
            }
        });
        getContentPane().add(cScroll, new org.netbeans.lib.awtextra.AbsoluteConstraints(58, 55, -1, 14));

        aView.setFont(new java.awt.Font("Arial Black", 0, 16)); // NOI18N
        aView.setText("50");
        getContentPane().add(aView, new org.netbeans.lib.awtextra.AbsoluteConstraints(264, 0, -1, -1));

        bView.setFont(new java.awt.Font("Arial Black", 0, 16)); // NOI18N
        bView.setText("50");
        getContentPane().add(bView, new org.netbeans.lib.awtextra.AbsoluteConstraints(262, 29, -1, -1));

        cView.setFont(new java.awt.Font("Arial Black", 0, 16)); // NOI18N
        cView.setText("50");
        getContentPane().add(cView, new org.netbeans.lib.awtextra.AbsoluteConstraints(262, 55, -1, -1));

        Result.setFont(new java.awt.Font("Arial", 2, 18)); // NOI18N
        Result.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        getContentPane().add(Result, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 90, 263, 100));

        jButton1.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jButton1.setText("CALCULAR");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 20, -1, -1));

        jLabel5.setFont(new java.awt.Font("Arial Black", 0, 18)); // NOI18N
        jLabel5.setText("a");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 100, 20, -1));
        jLabel5.getAccessibleContext().setAccessibleParent(null);

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/triangulo-removebg-preview.png"))); // NOI18N
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(-30, 30, -1, -1));

        jLabel6.setFont(new java.awt.Font("Arial Black", 0, 18)); // NOI18N
        jLabel6.setText("b");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 190, 20, -1));

        jLabel7.setFont(new java.awt.Font("Arial Black", 0, 18)); // NOI18N
        jLabel7.setText("c");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 100, 20, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void aScrollStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_aScrollStateChanged
        // TODO add your handling code here:
        int a = aScroll.getValue();
        aView.setText(Integer.toString(a));
    }//GEN-LAST:event_aScrollStateChanged

    private void bScrollStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_bScrollStateChanged
        // TODO add your handling code here:
        int b = bScroll.getValue();
        bView.setText(Integer.toString(b));
    }//GEN-LAST:event_bScrollStateChanged

    private void cScrollStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_cScrollStateChanged
        // TODO add your handling code here:
        int c = cScroll.getValue();
        cView.setText(Integer.toString(c));
    }//GEN-LAST:event_cScrollStateChanged

    private void aScrollAncestorAdded(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_aScrollAncestorAdded

    }//GEN-LAST:event_aScrollAncestorAdded

    private void aScrollAncestorMoved(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_aScrollAncestorMoved
        // TODO add your handling code here:zzz
    }//GEN-LAST:event_aScrollAncestorMoved

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        int a = aScroll.getValue();
        int b = bScroll.getValue();
        int c = cScroll.getValue();
        
        if ( a > 0 && b > 0 && c > 0  ){
            if ((a+b) > c && (a+c) > b && (b+c) > a){
                if (a==b && b==c){
                    Result.setText("<html> <center> <p>Esse Triangulo é possível<p> <p> <font color = 'red'> Ele é um triângulo <strong>Equilátero</strong> </font></p> </center> </html>");
                }
                else if (a == b || a == c || b == c){
                    Result.setText("<html> <center> <p>Esse Triangulo é possível<p> <p> <font color = 'red'> Ele é um triângulo <strong>Isósceles</strong> </font></p> </center> </html>");
                }
                else {
                    Result.setText("<html> <center> <p>Esse Triangulo é possível<p> <p> <font color = 'red'> Ele é um triângulo <strong>Escaleno</strong> </font></p> </center> </html>");
                }
            }
            else {
            Result.setText("<html><center>Esse triângulo não é possível</center></html>");
            }
        }
        else {
            Result.setText("<html><center>Esse triângulo não é possível</center></html>");
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainInterface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainInterface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainInterface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainInterface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainInterface().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Result;
    private javax.swing.JSlider aScroll;
    private javax.swing.JLabel aView;
    private javax.swing.JSlider bScroll;
    private javax.swing.JLabel bView;
    private javax.swing.JSlider cScroll;
    private javax.swing.JLabel cView;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    // End of variables declaration//GEN-END:variables
}
